Get latest commits from Upstream Fork (#1)
* Edit changelog

* Use remark-unwrap-images

* Adapt code highlighting to be customizable

* Add basic overview mode

* Add ThemeProvider to tests

* Add table styles

* Add Invert and Split layouts

* Add docs for layouts

* Edit Overview links

* Adjust syntax theme in demo

* 1.5.0

* Edit changelog

* 1.5.1

* Edit changelog

* Unfold all steps in overview mode

* 1.5.2

* Edit changelog

* Adjust overview mode styles

* Add cursor pointer to overview tiles

* 1.5.3

* Edit changelog

* Add docs for syntax highlighting

* Adjust default languages for syntax highlighting

* 1.5.4

* Edit changelog

* Add React component example

* Add default Provider

* Add buttons for basic mobile support

* Only show controls in normal mode

* Update snapshots

* Add script themes

* Edit readme

* Move external provider and components into theme

* Update documentation

* Add themes

* Add theme

* Update snapshots

* Update syntax highlighting documentation

* Update syntax highlighting documentation

* 1.5.5

* Edit changelog

* Add theme docs

* Edit themes docs

* Edit readme

* Adjust counter example styles

* 1.5.6

* Edit changelog

* Clean up comments

* Remove comments

* Provide fallback for existing implementations

* 1.5.7

* Edit changelog

* Clean up

* Split up docs

* Edit readme

* Add images to readme

* Edit readme

* Fix image in readme

* Edit theming docs

* Edit components docs

* Edit react docs

* Use the imported DefaultProvider

* Add advanced docs

* Edit advanced docs

* Fix links

* Add link to readme

* Typo

* Edit readme

* Edit changelog

* 1.5.8

* Fix links in docs

* Edit changelog

* 1.5.9

* Typo

* Adjust querystring parsing

* Rename Grid view

* Add new overview mode

* Adjust overview mode

* Edit docs

* Edit readme

* Edit readme

* Edit readme

* Update snapshots

* Edit changelog

* 1.5.10

* Add FullScreenCode layout

* Add docs for fullscreen code

* feat(src/index.js): Addding react-swippeable

* fix(index.js): Adding trackMouse flag to Swipeable

* chore(index.js): remove prettier changes

* test(index.js): Updating snapshots

* Adjust querystring updater

* Only add notes when rendered in the main view

* 1.5.11

* Update changelog

* 1.5.12

* Edit changelog

* 1.5.13

* Edit changelog

* Prevent last slide from cycling to beginning

* remove package-lock.json

* Add size prop to Image component

* Edit Image docs

* Update snapshots

* Undo img component changes

* 1.5.14

* Edit changelog

* Adjust pushState

* Add fallback in getMode method

* Update snapshot

* Remove inline snapshots

* Edit changelog

* 1.5.15

* Update Readme.md

Corrected the use of named export to default export for creating custom themes

* Update theming.md

Corrects the use of named import for default import

* corrects second instance of named import that should be default

* Add Head component and move webpack into repo

* Adjust entry for custom webpack setup

* Add head content to static output

* Add basic screenshot utility

* Build og image

* Adjust build and screenshot

* Edit docs

* Adjust travis config

* Update docs

* 1.6.0

* Edit changelog

* Adjust og image

* Add babel-code dependency

* 1.6.1

* Edit changelog

* Update mdx dependencies

* Adjust loader module parsing

* Remove unused vars

* Update package lock

* 1.6.2

* Update changelog

* Disable mouse swipe

* 1.6.3

* Edit changelog

* Removed comma from dev.js

I was having issues starting the server and then saw the extra comma.

```
> npm run start

> intern-project-pres@1.0.0 start /Users/benjaminmodayil/Documents/sites/intern-project-pres
> mdx-deck deck.mdx

[mdx-deck] starting dev server
/Users/benjaminmodayil/Documents/sites/intern-project-pres/node_modules/mdx-deck/lib/dev.js:26
  )
  ^
SyntaxError: Unexpected token )
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/benjaminmodayil/Documents/sites/intern-project-pres/node_modules/mdx-deck/cli.js:146:11)
```

* Add link to repository

* 1.6.4

* Edit changelog

* Fix slide index in Overview

* 1.6.5

* Edit changelog

* Left align pre tag – fixes #120

* Add CSS SSR support

* Add --no-html option

* Edit readme

* Edit changelog

* 1.6.6

* Make slide transitions themeable

* Update theming docs

* Use mkdirp

* 1.6.7

* Edit changelog

* Add init cli

* Edit readme

* Edit readme

* Edit readme

* Load custom webpack config file

* Update docs

* Add note about default mdx loader

* Fix slide index in presenter view

* Add mdx-deck to node-externals whitelist

* 1.6.8-0

* 1.6.8

* Edit changelog

* 1.6.9

* Edit changelog

* Consolidate context

* Split out updaters and constants

* Split out SlideDeck component

* Add failing tests

* Add new updaters

* Adjust notes context

* Adjust Appear component

* Adjust querystring parsing

* Edit docs

* Clarify docs

* 1.7.0-0

* Edit readme

* Export updaters and constants

* Edit keyboard shortcuts

* 1.7.0

* Edit changelog

* Potential fix for localStorage race condition

* 1.7.1

* Update changelog

* Add .gitignore to basic template

* Add example to readme

* Fix swipe direction

* Set overflow hidden on body and html

* Remove code surfer from demo

* Update deps

* 1.7.2

* 1.7.3

* Edit changelog